apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: "portinfos.paloaltonetworks.com"
spec:
  group: "paloaltonetworks.com"
  version: "v1alpha1"
  scope: "Namespaced"
  names:
    plural: "portinfos"
    singular: "portinfo"
    kind: "PortInfo"
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["portinfo"]
          properties:
           portinfo:
             type: "string"
             minimum: 1