apiVersion: v1
kind: Service
metadata:
  name: pan-ngfw-svc
  namespace: kube-system
  labels:
    app: pan-ngfw-svc
spec:
  ports:
  - protocol: UDP
    port: 6080
    name: panngfwsvc
  selector:
    app: pan-ngfw

