apiVersion: v1
kind: ConfigMap
metadata:
  name: pan-mgmt-config
  namespace: kube-system
data:
  PAN_SERVICE_NAME: pan-mgmt-svc
  PAN_MGMT_SECRET: pan-mgmt-secret

  # Panorama settings
  PAN_PANORAMA_IP: "<panorama-IP>"
  PAN_DEVICE_GROUP: "<panorama-device-group>"
  PAN_TEMPLATE_STACK: "<panorama-template-stack>"
  PAN_CGNAME: "<panorama-collector-group>"

  # Intended License Bundle type - "CN-X-BASIC", "CN-X-BND1", "CN-X-BND2"
  # based on the authcode applied on the Panorama K8S plugin"
  PAN_BUNDLE_TYPE: "<license-bundle-type>"

#Non-mandatory parameters
  # Recommended to have same name as the cluster name provided in Panorama Kubernetes plugin - helps with easier identification of pods if managing multiple clusters with same Panorama
  #CLUSTER_NAME: "<Cluster name>"

  #PAN_PANORAMA_IP2: ""
  
  # Comment out to use CERTs otherwise bypass encrypted connection to etcd in pan-mgmt.
  #ETCD_CERT_BYPASS: ""          # No value needed

  # Comment out to use CERTs otherwise PSK for IPSec between pan-mgmt and pan-ngfw
  #IPSEC_CERT_BYPASS: ""         # No values needed
