# Not required to specifiy ipam dhcp, will be handled by panos
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: net-attach-def-ci-gw
  namespace: kube-system
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "host-device",
      "pciBusID": "0000:00:07.0"
    }
