#Creating cluster role, namespace role and service account for pan-mgmt
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pan-mgmt-crole
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "list", "update", "delete"]
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests", "certificatesigningrequests/approval", "certificatesigningrequests/status"]
  verbs: ["get", "create", "list", "update", "delete"]
- apiGroups: ["certificates.k8s.io"]
  resources: ["signers"]
  resourceNames:
  # Support legacy versions, before signerName was added
  - "kubernetes.io/legacy-unknown"
  # Support Kubernetes built-in signer
  - "kubernetes.io/kube-apiserver-client"
  verbs: ["approve"]
- apiGroups: ["paloaltonetworks.com"]
  resources: ["panslotconfigs"]
  verbs: ["get", "create", "list", "update", "delete"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pan-mgmt-crb-kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pan-mgmt-crole
subjects:
- kind: ServiceAccount
  name: pan-mgmt-sa
  namespace: kube-system
---


apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pan-mgmt-role
  namespace: kube-system # Should be namespace pan-mgmt is deployed in
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - persistentvolumeclaims
  verbs:
  - get
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pan-mgmt-rb-kube-system
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pan-mgmt-role
subjects:
- namespace: kube-system
  kind: ServiceAccount
  name: pan-mgmt-sa
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: pan-mgmt-sa
  namespace: kube-system
