apiVersion: "paloaltonetworks.com/v1alpha1"
kind: "PanSlotConfig"
metadata:
  name: "pan-mgmt-svc-slots" # Name should match the MP service - "mpservicename-slots"
  namespace: kube-system
spec:
  slot: ""
  slotinfo : ""

