apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: "panslotconfigs.paloaltonetworks.com"
spec:
  group: "paloaltonetworks.com"
  version: "v1alpha1"
  scope: "Namespaced"
  names:
    plural: "panslotconfigs"
    singular: "panslotconfig"
    kind: "PanSlotConfig"
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["slot","slotinfo"]
          properties:
           slot:
             type: "string"
             minimum: 1
           slotinfo:
             type: "string"
             minimum: 1

