apiVersion: v1
kind: ConfigMap
metadata:
  name: pan-ngfw-config-1
  namespace: kube-system
data:
  PAN_SERVICE_NAME: pan-mgmt-svc-1    # should match the pan-cn-mgmt.yaml's Service name
  FAILOVER_MODE: failclose            # licensing failure behavior
  DP_RINGBUFFER: "60000"            # buffer count for memory/performance control
  PAN_CTNR_MODE_TYPE: "k8s-cnf"
  #PAN_DATA_MODE: "dpdk"            # HUGEPAGE_MEMORY_REQUEST is also needed
  #HUGEPAGE_MEMORY_REQUEST: "4096"  # in MB - needed for DPDK mode - should be same as hugepage request in pan-cn-ngfw.yaml - might change after 1.20
                                    # Refer to the system requirements documentation to see the minimum value needed for different capacity profiles.
  
  # Comment out to use CERTs otherwise PSK for IPSec between pan-mgmt and pan-ngfw
  #IPSEC_CERT_BYPASS: ""            # No values needed
  
  #IPSEC_NAT_PORT_RANGE: "4500-4500"    # port range to avoid stale connections

  # Enable/Disable cpu pinning of the forwarding processes (default physical
  # cpus) (different from K8S cpu pinning of the pods)
  PAN_CPU_PINNING_ENABLED: "false"

  # When doing cpu pinning of forwarding processes, use single NUMA node
  #PAN_NUMA_ENABLED: "<numa node number>"

  # When doing cpu pinning of forwarding processes, use logical cpus as well
  #PAN_HYPERTHREADING_ENABLED: "true"
      
  # When doing cpu pinning of forwarding processes, skip the lower numbered cpus
  # and start from this cpu
  #PAN_CPU_PINNING_BASE: "1"
