
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pan-plugin-crole
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - nodes
  - pods
  - services
  - secrets
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pan-plugin-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pan-plugin-crole
subjects:
- kind: ServiceAccount
  name: pan-plugin-user
  namespace: kube-system
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: pan-plugin-user
  namespace: kube-system
  labels:
    app: pan-plugin
---

apiVersion: v1
kind: Secret
metadata:
  name: pan-plugin-cluster-mode-secret
  namespace: kube-system
type: Opaque
stringData:
  CLUSTER_MODE: "K8S_DEPLOYMENT"
