#Create a SP before applying this yaml
# az ad sp create-for-rbac -n "<name of service principal>" --role "Monitoring Reader" --scopes /subscriptions/<sub-id>/resourceGroups/<resource-group-name>
#{
#  "appId": "be00cda9-7677-4964-adff-0eb16105bc09", — azure-client-id
#  "displayName": "djayarama",
#  "name": "http://djayarama",
#  "password": "85291172-1766-4efb-8209-2cefde9f28f4", - azure-client-secret
#  "tenant": "66b66353-3b76-4e41-9dc3-fee328bd400e" - azure-tenant-id
#}
# For appinsights-appid go to APP Insight -> API Access -> Application ID
# For appinsights-key go to APP Insight -> API Access -> Create API Key -> copy the KEY obtained
apiVersion: v1
kind: Namespace
metadata:
    name: "custom-metrics"

apiVersion: v1
kind: Secret
metadata:
  name: azure-k8s-metrics-adapter-secret
  namespace: custom-metrics
type: Opaque
stringData:
  appinsights-appid: "<Azure App Insight Application ID obtained from API Access>"
  appinsights-key: "<Azure App Insight API Key created under API Access>"
  azure-client-id: "<Azure SP APP ID associated with corresponding resource group with monitoring reader access>"
  azure-client-secret: "<Azure SP Password associated with corresponding resource group with monitoring reader access>"
  azure-tenant-id: "<Azure SP tenant ID associated with corresponding resource group with monitoring reader access>"
