apiVersion: v1
kind: Namespace
metadata:
    name: "custom-metrics"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: azure-k8s-metrics-adapter
  namespace: "custom-metrics"
  labels:
    app: azure-k8s-metrics-adapter
    chart: azure-k8s-metrics-adapter-0.1.0
    release: azure-k8s-metrics-adapter
    heritage: Tiller

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: externalmetrics.azure.com
spec:
  group: azure.com
  version: v1alpha2
  scope: Namespaced
  names:
    plural: externalmetrics
    singular: externalmetric
    kind: ExternalMetric
    shortNames:
    - aem
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: custommetrics.azure.com
spec:
  group: azure.com
  version: v1alpha2
  scope: Namespaced
  names:
    plural: custommetrics
    singular: custommetric
    kind: CustomMetric
    shortNames:
    - acm
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: azure-k8s-metrics-adapter
  labels:
    app: azure-k8s-metrics-adapter
    chart: azure-k8s-metrics-adapter-0.1.0
    release: azure-k8s-metrics-adapter
    heritage: Tiller
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - services
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: azure-k8s-metrics-adapter:custom-metrics-reader
  labels:
    app: azure-k8s-metrics-adapter
    chart: azure-k8s-metrics-adapter-0.1.0
    release: azure-k8s-metrics-adapter
    heritage: Tiller
rules:
- apiGroups:
  - custom.metrics.k8s.io
  resources: ["*"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: azure-k8s-metrics-adapter:external-metrics-reader
  labels:
    app: azure-k8s-metrics-adapter
    chart: azure-k8s-metrics-adapter-0.1.0
    release: azure-k8s-metrics-adapter
    heritage: Tiller
rules:
- apiGroups:
  - "external.metrics.k8s.io"
  resources:
  - "*"
  verbs:
  - list
  - get
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: azure-k8s-metrics-adapter:crd-metrics-reader
  labels:
    app: azure-k8s-metrics-adapter
    chart: azure-k8s-metrics-adapter-0.1.0
    release: azure-k8s-metrics-adapter
    heritage: Tiller
rules:
- apiGroups:
  - azure.com
  resources:
  - "externalmetrics"
  - "custommetrics"
  verbs:
  - list
  - get
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: azure-k8s-metrics-adapter:system:auth-delegator
  namespace: kube-system #ensure it is the same namespace where mp is deployed
  labels:
    app: azure-k8s-metrics-adapter
    chart: azure-k8s-metrics-adapter-0.1.0
    release: azure-k8s-metrics-adapter
    heritage: Tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - name: azure-k8s-metrics-adapter
    namespace: "custom-metrics"
    kind: ServiceAccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: azure-k8s-metrics-adapter
  labels:
    app: azure-k8s-metrics-adapter
    chart: azure-k8s-metrics-adapter-0.1.0
    release: azure-k8s-metrics-adapter
    heritage: Tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: azure-k8s-metrics-adapter
subjects:
  - name: azure-k8s-metrics-adapter
    namespace: "custom-metrics"
    kind: ServiceAccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: azure-k8s-metrics-adapter:hpa-external-metrics-reader
  labels:
    app: azure-k8s-metrics-adapter
    chart: azure-k8s-metrics-adapter-0.1.0
    release: azure-k8s-metrics-adapter
    heritage: Tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: azure-k8s-metrics-adapter:external-metrics-reader
subjects:
  - kind: ServiceAccount
    name: horizontal-pod-autoscaler
    namespace: kube-system #ensure it is the same namespace where mp is deployed
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: azure-k8s-metrics-adapter:hpa-custom-metrics-reader
  labels:
    app: azure-k8s-metrics-adapter
    chart: azure-k8s-metrics-adapter-0.1.0
    release: azure-k8s-metrics-adapter
    heritage: Tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: azure-k8s-metrics-adapter:custom-metrics-reader
subjects:
  - kind: ServiceAccount
    name: horizontal-pod-autoscaler
    namespace: kube-system #ensure it is the same namespace where mp is deployed
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: azure-k8s-metrics-adapter:crd-metrics-reader
  labels:
    app: azure-k8s-metrics-adapter
    chart: azure-k8s-metrics-adapter-0.1.0
    release: azure-k8s-metrics-adapter
    heritage: Tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: azure-k8s-metrics-adapter:crd-metrics-reader
subjects:
  - name: azure-k8s-metrics-adapter
    namespace: "custom-metrics"
    kind: ServiceAccount
---

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: azure-k8s-metrics-adapter:extension-apiserver-authentication-reader
  labels:
    app: azure-k8s-metrics-adapter
    chart: azure-k8s-metrics-adapter-0.1.0
    release: azure-k8s-metrics-adapter
    heritage: Tiller
  namespace: kube-system #ensure it is the same namespace where mp is deployed
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: azure-k8s-metrics-adapter
  namespace: "custom-metrics"

---
apiVersion: v1
kind: Service
metadata:
  name: azure-k8s-metrics-adapter
  namespace: "custom-metrics"
  labels:
    app: azure-k8s-metrics-adapter
    chart: azure-k8s-metrics-adapter-0.1.0
    release: azure-k8s-metrics-adapter
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: azure-k8s-metrics-adapter
    release: azure-k8s-metrics-adapter

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-k8s-metrics-adapter
  namespace: "custom-metrics"
  labels:
    app: azure-k8s-metrics-adapter
    chart: azure-k8s-metrics-adapter-0.1.0
    release: azure-k8s-metrics-adapter
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-k8s-metrics-adapter
      release: azure-k8s-metrics-adapter
  template:
    metadata:
      labels:
        app: azure-k8s-metrics-adapter
        release: azure-k8s-metrics-adapter
    spec:
      serviceAccountName: azure-k8s-metrics-adapter
      imagePullSecrets:
        - name: registryCredentials
      containers:
        - name: azure-k8s-metrics-adapter
          image: "mcr.microsoft.com/k8s/metrics/adapter:latest"
          imagePullPolicy: Always
          args:
            - /adapter
            - --secure-port=6443
            - --logtostderr=true
            - --v=2
          ports:
            - name: http
              containerPort: 6443
              protocol: TCP
          env:
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: azure-k8s-metrics-adapter-secret
                  key: azure-tenant-id
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: azure-k8s-metrics-adapter-secret
                  key: azure-client-id
            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: azure-k8s-metrics-adapter-secret
                  key: azure-client-secret
            - name: APP_INSIGHTS_KEY
              valueFrom:
                secretKeyRef:
                  name: azure-k8s-metrics-adapter-secret
                  key: appinsights-key
            - name: APP_INSIGHTS_APP_ID
              valueFrom:
                secretKeyRef:
                  name: azure-k8s-metrics-adapter-secret
                  key: appinsights-appid
          volumeMounts:
            - mountPath: /tmp
              name: temp-vol
          resources:
            {}
            
      volumes:
        - name: temp-vol
          emptyDir: {}

---
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.custom.metrics.k8s.io
spec:
  service:
    name: azure-k8s-metrics-adapter
    namespace: custom-metrics
  group: custom.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
---
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.external.metrics.k8s.io
spec:
  service:
    name: azure-k8s-metrics-adapter
    namespace: custom-metrics
  group: external.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
